"""Versioned, validated seed for the Bolhão purchasing catalogue.

The workbook is the preparation source only. Runtime imports use this module so
new environments and production do not depend on the uploaded file.
"""

CATALOG_SOURCE = 'bolhao_lista_compras'
CATALOG_VERSION = 'bolhao-initial-v1'

# (source_row, origin_label, product, brand)
CATALOG_ROWS = (
    (8, 'Makro', 'Canela em pó 500g', None),
    (9, 'Makro', 'Mel (kg)', None),
    (10, 'Makro', 'Granola (pacote com 800g)', None),
    (11, 'Makro', 'Bolacha Maria (pacote com 800g)', None),
    (12, 'Makro', 'Açúcar para Café sachê', None),
    (13, 'Makro', 'Adoçante para Café sachê', None),
    (14, 'Makro', 'Álcool 96% 100ml', None),
    (15, 'Makro', 'Esponja und.', None),
    (16, 'Makro', 'Papel vegetal', None),
    (17, 'Makro', 'Saco congelação 1 l', None),
    (18, 'Makro', 'Saco congelação 3l', None),
    (19, 'Makro', 'Cheirinho casa de banho Spray', None),
    (20, 'Makro', 'Lixívia Spray', None),
    (21, 'Makro', 'Detergente louça 4l', None),
    (22, 'Makro', 'Caneta permanente preta (und)', None),
    (23, 'Makro', 'Espatula para fazer bola', None),
    (24, 'Makro', 'Recipiente de inox para aquecer leite', None),
    (25, 'Makro', 'Recipiente de inox para crumble', None),
    (26, 'Makro', 'Neoblanc - Tira manchas (2l)', None),
    (27, 'Porto Higiene', 'Rolo de papel térmico 80x60x11 (caixa - 10 und.)', None),
    (28, 'Porto Higiene', 'Rolo de papel térmico 57x40x11 (cartão - 10 und. )', None),
    (29, 'Porto Higiene', 'Luva S (caixa)', None),
    (30, 'Porto Higiene', 'Luva M (caixa)', None),
    (31, 'Porto Higiene', 'Luva L (caixa)', None),
    (32, 'Porto Higiene', 'Saco de lixo 5l (pct - 10und)', None),
    (33, 'Porto Higiene', 'Saco de lixo 50l (pct -10 und)', None),
    (34, 'Porto Higiene', 'Saco de lixo 100l (pct - 10Und.)', None),
    (35, 'Porto Higiene', 'Película Aderente', None),
    (36, 'Porto Higiene', 'Pezinhos/Protetor de calçados', None),
    (37, 'Porto Higiene', 'Sabonete WC (und - 5l)', None),
    (38, 'Porto Higiene', 'Abrilhantador máquina de louça (und - 5l)', None),
    (39, 'Porto Higiene', 'Desinfetante para superfícies Ecomix', 'Ecomix'),
    (40, 'Porto Higiene', 'Detergente máquina de lavar louça (und - 5l)', None),
    (41, 'Porto Higiene', 'Desinfetante VT 10 - Álcool 70% (und - 5l)', None),
    (42, 'Porto Higiene', 'Desinfetante WC - Solim  (und - 5l)', None),
    (43, 'Porto Higiene', 'Desinfetante chão - Bioalcool (und - 5l)', None),
    (44, 'Porto Higiene', 'Descalcificador (und - 5l)', None),
    (45, 'Porto Higiene', 'Guardanapos tipo L caixa', None),
    (46, 'Porto Higiene', 'Papel Autocorte (6 und)', None),
    (47, 'Porto Higiene', 'Papel Zigzag', None),
    (48, 'Porto Higiene', 'Papel Higiênico (12 und)', None),
    (49, 'Porto Higiene', 'Touca preta redinha - (100 und)', None),
    (50, 'Greenpack', 'Tampas capuccino', None),
    (51, 'Greenpack', 'Tampa Milkshake', None),
    (52, 'Greenpack', 'Saco de papel kraft para cones', None),
    (53, 'Greenpack', 'Sacos de cookies', None),
    (54, 'Greenpack', 'Saco plástico para pastelaria', None),
    (55, 'Greenpack', 'Pratinho para Nivottos', None),
    (56, 'Greenpack', 'Copo para Água', None),
    (57, 'Greenpack', 'Copos takeway kraft com tampa', None),
    (58, 'Greenpack', 'Agitador Café embalada indivialmente 9cm', None),
    (59, 'Greenpack', 'Caixa Kraft 12x10x4,5 500ml', None),
    (60, 'Greenpack', 'Caixa Kraft 12x10x4,5 1050ml', None),
    (61, 'Sumol Compal', 'Água sem gás 330ml (Unidade)', None),
    (62, 'Sumol Compal', 'Água com gás frize (Unidade)', None),
    (63, 'Sumol Compal', 'Frizze limão (Unidade)', None),
    (64, 'Sumol Compal', 'Frizze maracujá (Unidade)', None),
    (65, 'Sumol Compal', 'Frizze laranja (Unidade)', None),
    (66, 'Sumol Compal', 'Pepsi (Unidade)', None),
    (67, 'Sumol Compal', 'Pepsi zero (Unidade)', None),
    (68, 'Sumol Compal', 'Compal maga/laranja (Unidade)', None),
    (69, 'Sumol Compal', 'Compal pêssego (Unidade)', None),
    (70, 'SUVITA', 'Caixa Take Away 500g', None),
    (71, 'SUVITA', 'Caixa Take Away 1000g', None),
    (72, 'SUVITA', 'Caixa Take Away 1500g', None),
    (73, 'SUVITA', 'Pistacchio em pedaços', None),
    (74, 'SUVITA', 'Colheres para gelado', None),
    (75, 'SUVITA', 'Cone pequeno 40" (caixa 480 und)', None),
    (76, 'SUVITA', 'Cone Médio 45" (caixa 420 und.)', None),
    (77, 'LACTOGAL', 'Leite inteiro Gresso (l)', None),
    (78, 'LACTOGAL', 'Manteiga com sal Gresso (kg)', None),
    (79, 'MATOSINHOS', 'Copo piccolo (manga- 50und)', None),
    (80, 'MATOSINHOS', 'Copo classico (manga- 50und)', None),
    (81, 'MATOSINHOS', 'Copo grande (manga- 50und)', None),
    (82, 'MATOSINHOS', 'Copo max (manga- 50und)', None),
    (83, 'MATOSINHOS', 'Copo peso (manga- 50und)', None),
    (84, 'MATOSINHOS', 'Copo Café (manga- 50und)', None),
    (85, 'MATOSINHOS', 'Copo Cappucino/Branco Nivà (manga- 50und)', None),
    (86, 'MATOSINHOS', 'Copo Milkshake (manga- 50und)', None),
    (87, 'MATOSINHOS', 'Colheres brancas cartão Açaí', None),
    (88, 'MATOSINHOS', 'Guardanapos Nivà', None),
    (89, 'MATOSINHOS', 'Ricotta (kg)', None),
    (90, 'MATOSINHOS', 'Cannolo (und)', None),
    (91, 'MATOSINHOS', 'Chocolate 64% (Cannolo)', None),
    (92, 'MATOSINHOS', 'Brioche (und.)', None),
    (93, 'MATOSINHOS', 'Saco Nivà (und)', None),
    (94, 'MATOSINHOS', 'Fita Niva caixas Take away (rolo)', None),
    (95, 'MATOSINHOS', 'Capa para cone/Porta cones roxo', None),
    (96, 'MATOSINHOS', 'Cerejas em calda', None),
    (97, 'MATOSINHOS', 'Esfregona', None),
    (98, 'MATOSINHOS', 'Palhinha milkshake', None),
    (99, 'MATOSINHOS', 'Pote takeway p/ amarena', None),
    (100, 'MATOSINHOS', 'Envelope branco 110x220mm', None),
    (101, 'MATOSINHOS', 'Cacau em pó', None),
    (102, 'MATOSINHOS', 'Adesivo Nivá redondo Pequeno', None),
    (103, 'MATOSINHOS', 'Post it', None),
    (104, 'MATOSINHOS', 'Açúcar de Confeiteiro', None),
    (105, 'MATOSINHOS', 'Band-aid/Penso', None),
    (106, 'Progelcone', 'Mini Cone', None),
    (107, 'CAFÉ ILLY', 'Café Classico', None),
    (108, 'CAFÉ ILLY', 'Descafeinado', None),
    (109, 'GRÁFICA', 'Higienização Armazém', None),
    (110, 'GRÁFICA', 'Limpeza WC', None),
    (111, 'GRÁFICA', 'Limpeza área clientes', None),
    (112, 'GRÁFICA', 'Limpeza zona de produção', None),
    (113, 'GRÁFICA', 'Rastreabilidade', None),
    (114, 'GRÁFICA', 'Entrada de mercadorias', None),
    (115, 'GRÁFICA', 'Fecho de caixa', None),
    (116, 'MOEDAS', '0,10€', None),
    (117, 'MOEDAS', '0,20€', None),
    (118, 'MOEDAS', '0,50€', None),
    (119, 'MOEDAS', '1,0€', None),
    (120, 'MOEDAS', '2,0€', None),
)