// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scoopy-brand/AppIcon.tsx": () => import("../components/mockups/scoopy-brand/AppIcon.tsx"),
  "./components/mockups/scoopy-brand/BusinessCard.tsx": () => import("../components/mockups/scoopy-brand/BusinessCard.tsx"),
  "./components/mockups/scoopy-brand/ColorPalette.tsx": () => import("../components/mockups/scoopy-brand/ColorPalette.tsx"),
  "./components/mockups/scoopy-brand/LogoModern.tsx": () => import("../components/mockups/scoopy-brand/LogoModern.tsx"),
  "./components/mockups/scoopy-brand/LogoPlayful.tsx": () => import("../components/mockups/scoopy-brand/LogoPlayful.tsx"),
  "./components/mockups/scoopy-brand/ScoopyPresentation.tsx": () => import("../components/mockups/scoopy-brand/ScoopyPresentation.tsx"),
  "./components/mockups/scoopy-brand/SocialPost.tsx": () => import("../components/mockups/scoopy-brand/SocialPost.tsx")
};
